# Docker compose version https://docs.docker.com/compose/compose-file
version: "3.9"

# Define SonarQube and PostgreSQL services.
services:
  # SonarQube server.
  sonarqube:
    image: sonarqube:lts-community
    container_name: sonarqube
    depends_on:
      - sonarqube-db
    environment:
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: "true"
      SONAR_JDBC_URL: jdbc:postgresql://sonarqube-db:5432/sonarqube
      SONAR_SEARCH_JAVAADDITIONALOPTS: "-Dbootstrap.system_call_filter=false"
      SONAR_JDBC_USERNAME: sonarqubeUser
      SONAR_JDBC_PASSWORD: sonar
    networks:
      - sonarqube
    # Enable platform for Apple Silicon.
    platform: linux/x86_64
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_temp:/opt/sonarqube/temp
    ports:
      - 9000:9000

  # SonarQube database.
  sonarqube-db:
    image: postgres:latest
    container_name: sonarqube-db
    environment:
      POSTGRES_DB: sonarqube
      POSTGRES_USER: sonarqubeUser
      POSTGRES_PASSWORD: sonar
    networks:
      - sonarqube
    # Enable platform for Apple Silicon.
    platform: linux/x86_64
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data

# Define network for SonarQube, PostgreSQL and SonnarScanner containers.
networks:
  sonarqube:
    name: sonarqube-network
    driver: bridge

# Define volumes for containers.
volumes:
  sonarqube_data:
    name: sonarqube_data
  sonarqube_extensions:
    name: sonarqube_extensions
  sonarqube_logs:
    name: sonarqube_logs
  sonarqube_temp:
    name: sonarqube_temp
  postgresql:
    name: postgresql
  postgresql_data:
    name: postgresql_data
