name: ShellCheck Analysis

on:
  push:
    paths:
      - '.github/workflows/**'
      - 'bin/**'
  pull_request:
    paths:
      - '.github/workflows/**'
      - 'bin/**'

jobs:
  shellcheck:
    name: Shellcheck analysis
    runs-on: ubuntu-latest

    concurrency:
      group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
      cancel-in-progress: true

    steps:
      - name: Checkout the Git repository
        uses: actions/checkout@v4

      - name: Run ShellCheck analysis
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: './bin'
